config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#root"

  resources :users, only: [:new, :create, :destroy]
  resource :session, only: [:new, :destroy, :create]

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:index, :show, :update]
    resources :topics, only: [:show, :create, :destroy, :index]
    resources :posts, only: [:show, :create, :destroy, :index]
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :user_id, presence: true
  validates :topic_id, presence: true
  validates :body, presence: true
  validates_length_of :body, :minimum => 3, :maximum => 1000, :allow_blank => false

  belongs_to :topic,
  primary_key: :id,
  foreign_key: :topic_id,
  class_name: "Topic"

  belongs_to :user,
  primary_key: :id,
  foreign_key: :user_id,
  class_name: "User"
end

app/models/topic.rb
class Topic < ActiveRecord::Base

  validates :user_id, presence: true
  validates :title, presence: true
  validates_length_of :title, :minimum => 3, :maximum => 55, :allow_blank => false

  belongs_to :user,
  primary_key: :id,
  foreign_key: :user_id,
  class_name: "User"

  has_many :posts,
  primary_key: :id,
  foreign_key: :topic_id,
  class_name: "Post"

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  after_initialize :ensure_session_token

  has_many :topics,
  primary_key: :id,
  foreign_key: :user_id,
  class_name: "Topic"

  has_many :posts,
  primary_key: :id,
  foreign_key: :user_id,
  class_name: "Post"

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.valid_password?(password)
    user
  end

  def recently_logged_in?
    updated_at > 5.minutes.ago
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  before_filter :require_signed_in!

  def show
    @post = Post.find(params[:id])
  end

  def index
    search_terms = params[:post][:body].split(" ")
    @posts = []

    usernames = []
    User.all.each do |user|
      usernames.push(user.username)
    end

    if usernames.include?(params[:post][:body])
      if User.find_by({ username: params[:post][:body] })
        @user = User.find_by({ username: params[:post][:body] })
        @posts = @user.posts
      end
    else
      Post.all.each do |post|
        search_terms.each do |word|
          if post.body.split(" ").include?(word) && !(@posts.include?(post))
            @posts.push(post)
          end
        end
      end
    end

    @posts = @posts.reverse
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save!
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy!
  end

  private
  def post_params
    params.require(:post).permit(:topic_id, :body)
  end
end

app/controllers/api/topics_controller.rb
class Api::TopicsController < ApplicationController
  before_filter :require_signed_in!

  def index
    # @topics = Topic.all.reverse
    @topics = Topic.all.sort_by { |topic| topic.posts.last.created_at }.reverse
    # @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    @topic.save!

  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy!
    # render json: {}
  end

  private
  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  before_filter :require_signed_in!

  def index
    users = User.all
    @users = []

    users.each do |user|
      if user.recently_logged_in? || user.posts.last.created_at > 5.minutes.ago
        @users << user
      end
    end

    @users
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if params[:user][:public_id] != ""
      @user.public_id = params[:user][:public_id]
      @user.save!
    end

    if params[:user][:location] != ""
      @user.location = params[:user][:location]
      @user.save!
    end

    if params[:user][:about_me] != ""
      @user.about_me = params[:user][:about_me]
      @user.save!
    end

    @user
  end

  private
  def user_params
    params.require(:user).permit(:password, :username, :location, :about_me, :public_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :current_users, :signed_in?

  @@current_users ||= Array.new

  private

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_token!
  end

  def sign_out
    current_user.try(:reset_token!)
    session[:session_token] = nil
    # redirect_to new_session_url
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user
      sign_in(user)
      redirect_to root_url
    else
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    end
  end

  def destroy
    sign_out
    render json: { status: "signed out" }
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :require_signed_in!

  def root
    render :root
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy!
  end

  private
  def user_params
    params.require(:user).permit(:password, :username)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token_input
    "<input
        type=\"hidden\"
        name=\"authenticity_token\"
        value=\"#{ form_authenticity_token }\">".html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Messageboard</title>

  <link href='https://fonts.googleapis.com/css?family=Montserrat'
    rel='stylesheet'
    type='text/css'>
  <script
    src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js">
  </script>
  <script
    src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js">
  </script>

  <script src="//widget.cloudinary.com/global/all.js" type="text/javascript">
  </script>
  <script type="text/javascript">
    window.CLOUDINARY_OPTIONS = {
      upload_preset: "<%= ENV['UPLOAD_PRESET'] %>",
      cloud_name: "<%= ENV['CLOUD_NAME'] %>"
    }
    </script>

  <%= stylesheet_link_tag 'application', media: 'all' %>

  <%= csrf_meta_tags %>

</head>
<body>

<% if signed_in? %>
    <script type="text/javascript">
      window.current_user_id = <%= current_user.id %>;
    </script>

<% end %>

  <center>
    <%= render "layouts/errors" %>
    <%= yield %>
  </center>

</body>
</html>

app/views/static_pages/root.html.erb
<div class="full-page" id="root">

</div>
<%= javascript_include_tag 'application' %>

app/views/users/new.html.erb
<div class="login_slogan">
        Your life in pictures begins here
      </div>
      <form action="<%= users_url %>" method="post">
        <%= auth_token_input %>
          <input type="text"
                 maxLength="10"
                 class="login_username"
                 name="user[username]"
                 placeholder='New Username'
                 value="">
          <div class="bottom_pad"></div>
          <input type="password"
                   name="user[password]"
                   placeholder='New Password'
                   value=""
                   class="bottom_pad">
          <div class="bottom_pad"></div>
          <input type="submit" value="Sign Up!" class="login">
          <div class="bottom_pad"></div>
          <div class="bottom_pad"></div>
          <div class="bottom_pad"></div>
          <div class="bottom_pad"></div>


</form>
          <div class="guest_pad"> </div>
          <div class="login_text">

            <div class="login_switch_div">
              <div class="registered_text">
                Already registered?
              </div>
              <div class="sign_up_link">
                <%= link_to "Sign In!", new_session_url %>
              </div>
            </div>


          </div>